#!/bin/bash

# LinkedIn profile image downloader helper script
# Note: LinkedIn requires authentication, so this will guide you through the process

echo "LinkedIn Profile Image Download Helper"
echo "========================================"
echo ""
echo "LinkedIn profile images require authentication and cannot be downloaded automatically."
echo "Please follow these steps for each person:"
echo ""
echo "1. Open their LinkedIn profile in your browser (while logged in)"
echo "2. Right-click on their profile photo"
echo "3. Select 'Save image as...' or 'Copy image'"
echo "4. Save to: public/testimonials/<filename>.jpg"
echo ""
echo "Required downloads:"
echo ""
echo "1. Gourav Singal"
echo "   URL: https://www.linkedin.com/in/gourav-singal-680473185/"
echo "   Save as: public/testimonials/gourav-singal.jpg"
echo ""
echo "2. Ramana Satyavarapu"
echo "   URL: https://www.linkedin.com/in/ramana-satyavarapu/"
echo "   Save as: public/testimonials/ramana-satyavarapu.jpg"
echo ""
echo "3. Kuai Yu"
echo "   URL: https://www.linkedin.com/in/kuai/"
echo "   Save as: public/testimonials/kuai-yu.jpg"
echo ""
echo "4. Amit Tomar"
echo "   URL: https://www.linkedin.com/in/amittomar1/"
echo "   Save as: public/testimonials/amit-tomar.jpg"
echo ""
echo "5. Sourab Sharma"
echo "   URL: https://www.linkedin.com/in/sourab-sharma/"
echo "   Save as: public/testimonials/sourab-sharma.jpg"
echo ""
echo "6. Aaryaman Vir Shah"
echo "   URL: https://www.linkedin.com/in/aaryaman-vir-shah-15721952/"
echo "   Save as: public/testimonials/aaryaman-shah.jpg"
echo ""
echo "Note: The component will show initials if images are not found."
